# Generated by Django 4.1.7 on 2023-02-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_project_options_alter_project_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Service',
        ),
    ]
